package gui.frames.mainmenu;

import classes.gui.mainmenu.DashMenuItem;
import classes.gui.mainmenu.MenuTreeCellRenderer;
import javax.swing.tree.DefaultMutableTreeNode;
/**
 *
 * @author Ashraful Islam
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlBody = new javax.swing.JPanel();
    pnlMenu = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    // define root node
    DefaultMutableTreeNode menu = new DefaultMutableTreeNode("Menu");

    // define sales node
    DefaultMutableTreeNode sales = new DefaultMutableTreeNode(new DashMenuItem("Sales","dash_menu_sale_root.png"));
    // define sub-nodes for sales
    sales.add(new DefaultMutableTreeNode(new DashMenuItem("Sale", "dash_menu_sale_register.png")));
    sales.add(new DefaultMutableTreeNode(new DashMenuItem("Exchange", "dash_menu_sale_return.png")));

    // define stock node
    DefaultMutableTreeNode stock = new DefaultMutableTreeNode(new DashMenuItem("Stock","dash_menu_buy_root.png"));
    // add sub-nodes for stock
    stock.add(new DefaultMutableTreeNode(new DashMenuItem("Order", "dash_menu_buy_restock.png")));
    stock.add(new DefaultMutableTreeNode(new DashMenuItem("Return", "dash_menu_buy_return.png")));

    // define report node
    DefaultMutableTreeNode report = new DefaultMutableTreeNode(new DashMenuItem("Reports","dash_menu_rep_root.png"));
    // add sub-nodes for report
    report.add(new DefaultMutableTreeNode(new DashMenuItem("Sales", "dash_menu_rep_sale.png")));
    report.add(new DefaultMutableTreeNode(new DashMenuItem("Stock", "dash_menu_rep_stock.png")));

    // define product node
    DefaultMutableTreeNode product = new DefaultMutableTreeNode(new DashMenuItem("Products","dash_menu_product_root.png"));
    // add sub-nodes for product
    product.add(new DefaultMutableTreeNode(new DashMenuItem("Products", "dash_menu_product_list.png")));
    product.add(new DefaultMutableTreeNode(new DashMenuItem("Categories", "dash_menu_product_category.png")));
    product.add(new DefaultMutableTreeNode(new DashMenuItem("Units", "dash_menu_product_unit.png")));
    product.add(new DefaultMutableTreeNode(new DashMenuItem("Price", "dash_menu_product_price.png")));

    // define records node
    DefaultMutableTreeNode record = new DefaultMutableTreeNode(new DashMenuItem("Records","dash_menu_rec_root.png"));
    // add sub-nodes for records
    record.add(new DefaultMutableTreeNode(new DashMenuItem("Customers", "dash_menu_rec_customers.png")));
    record.add(new DefaultMutableTreeNode(new DashMenuItem("Employees", "dash_menu_rec_employee.png")));
    record.add(new DefaultMutableTreeNode(new DashMenuItem("Suppliers", "dash_menu_rec_supplier.png")));

    // define config node
    DefaultMutableTreeNode config = new DefaultMutableTreeNode(new DashMenuItem("Settings","dash_menu_conf_root.png"));
    // add sub-nodes for config
    config.add(new DefaultMutableTreeNode(new DashMenuItem("Access", "dash_menu_conf_privilege.png")));
    config.add(new DefaultMutableTreeNode(new DashMenuItem("Offers", "dash_menu_conf_offer.png")));

    // add all nodes to root-menu
    menu.add(sales);
    menu.add(stock);
    menu.add(product);
    menu.add(record);
    menu.add(report);
    menu.add(config);

    // add root node(via constructor) to tree
    dashMenu = new javax.swing.JTree(menu);
    pnlHeader = new javax.swing.JPanel();
    lblLocation = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Open POS . Dashboard");
    setAlwaysOnTop(true);
    setBackground(new java.awt.Color(30, 170, 241));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setForeground(java.awt.Color.lightGray);
    setIconImages(null);
    setMaximumSize(new java.awt.Dimension(440, 580));
    setMinimumSize(new java.awt.Dimension(440, 580));
    setName("dashMain"); // NOI18N
    setPreferredSize(null);
    setResizable(false);
    getContentPane().setLayout(null);

    pnlBody.setBackground(new java.awt.Color(240, 243, 246));

    // custom cell renderer
    MenuTreeCellRenderer mtcr = new MenuTreeCellRenderer();

    // use custom cell renderer
    dashMenu.setCellRenderer(mtcr);
    dashMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 0, 0));
    dashMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    dashMenu.setForeground(new java.awt.Color(255, 255, 255));
    dashMenu.setModel(dashMenu.getModel());
    dashMenu.setDoubleBuffered(true);
    dashMenu.setMinimumSize(new java.awt.Dimension(74, 78));
    dashMenu.setName(""); // NOI18N
    dashMenu.setRootVisible(false);
    dashMenu.setRowHeight(24);
    jScrollPane1.setViewportView(dashMenu);

    javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
    pnlMenu.setLayout(pnlMenuLayout);
    pnlMenuLayout.setHorizontalGroup(
      pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    pnlMenuLayout.setVerticalGroup(
      pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
    pnlBody.setLayout(pnlBodyLayout);
    pnlBodyLayout.setHorizontalGroup(
      pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlBodyLayout.createSequentialGroup()
        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(314, Short.MAX_VALUE))
    );
    pnlBodyLayout.setVerticalGroup(
      pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    getContentPane().add(pnlBody);
    pnlBody.setBounds(0, 35, 440, 520);

    pnlHeader.setBackground(new java.awt.Color(215, 221, 228));

    lblLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/header_icon_location.png"))); // NOI18N
    lblLocation.setText("Dashboard");

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/header_icon_logout.png"))); // NOI18N
    jLabel1.setText("Logout");

    javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
    pnlHeader.setLayout(pnlHeaderLayout);
    pnlHeaderLayout.setHorizontalGroup(
      pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlHeaderLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblLocation)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addContainerGap())
    );
    pnlHeaderLayout.setVerticalGroup(
      pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlHeaderLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblLocation)
          .addComponent(jLabel1))
        .addContainerGap(13, Short.MAX_VALUE))
    );

    getContentPane().add(pnlHeader);
    pnlHeader.setBounds(0, 0, 440, 40);

    getAccessibleContext().setAccessibleName("Open POS | Dashboard");

    pack();
  }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

              new Dashboard().setVisible(true);

            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTree dashMenu;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblLocation;
  private javax.swing.JPanel pnlBody;
  private javax.swing.JPanel pnlHeader;
  private javax.swing.JPanel pnlMenu;
  // End of variables declaration//GEN-END:variables
}
